version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS  --password-stdin 445976816567.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=445976816567.dkr.ecr.us-east-1.amazonaws.com/redshiftdevops
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:redshiftdevops .
      - docker tag $REPOSITORY_URI:redshiftdevops $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:redshiftdevops
      - docker push $REPOSITORY_URI:$IMAGE_TAG